function mvpdemo(){var P='',xb='" for "gwt:onLoadErrorFn"',vb='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',jc='.cache.html',_='/',lb='//',ac='30AAE5691B7BC6082E48D3F90C566F2C',bc='394D6FAE47E5DCCDB6620060992D4A2A',cc='3C4F9FF2006FA544027AC6FEEF243315',dc='69AF3A56E5B4863229AE758B5F9CB919',ec='8CF5E7F5286242DBA73BA505226C7767',ic=':',pb='::',lc='<script defer="defer">mvpdemo.onInjectionDone(\'mvpdemo\')<\/script>',hb='<script id="',sb='=',$='?',ub='Bad handler "',fc='D9A9E20B7A41B927FA8E636C40FE0B27',kc='DOMContentLoaded',gc='EF8D5AB926A07E7725A06EDD85962556',hc='F43C4271FDFE2F1647A151699903E854',jb='SCRIPT',gb='__gwt_marker_mvpdemo',Gb='android',kb='base',cb='baseUrl',T='begin',Kb='blackberry',S='bootstrap',bb='clear.cache.gif',rb='content',Y='end',Lb='file://',Wb='gecko',Xb='gecko1_8',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',wb='gwt:onLoadErrorFn',tb='gwt:onPropertyErrorFn',qb='gwt:property',$b='hosted.html?mvpdemo',Vb='ie6',Ub='ie8',Tb='ie9',yb='iframe',ab='img',Hb='ipad',Jb='iphone',Ib='ipod',zb="javascript:''",Zb='loadExternalRefs',mb='meta',Cb='mobile.user.agent',Db='mobilesafari',Bb='moduleRequested',X='moduleStartup',Sb='msie',Q='mvpdemo',eb='mvpdemo.nocache.js',ob='mvpdemo::',nb='name',Nb='no',Eb='not_mobile',Pb='opera',Fb='phonegap.env',Ab='position:absolute;width:0;height:0;border:none',Rb='safari',db='script',_b='selectingPermutation',R='startup',fb='undefined',Yb='unknown',Ob='user.agent',Qb='webkit',Mb='yes';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=P,u={},v=[],w=[],x=[],y=0,z,A;o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function B(){var b=false;try{var c=m.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}B=function(){return b};return b}
function C(){if(q&&r){var b=n.getElementById(Q);var c=b.contentWindow;if(B()){c.__gwt_getProperty=function(a){return H(a)}}mvpdemo=null;c.gwtOnLoad(z,Q,t,y);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function D(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=F(cb);if(a!=null){return a}return P}
function h(){var a=n.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;n.write(hb+b+ib);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=n.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
function k(){var a=n.location;return a.href==a.protocol+lb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==P){l=h()}if(l==P){l=i()}if(l==P){l=j()}if(l==P&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function E(){var b=document.getElementsByTagName(mb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(nb),g;if(f){f=f.replace(ob,P);if(f.indexOf(pb)>=0){continue}if(f==qb){g=e.getAttribute(rb);if(g){var h,i=g.indexOf(sb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}u[f]=h}}else if(f==tb){g=e.getAttribute(rb);if(g){try{A=eval(g)}catch(a){alert(ub+g+vb)}}}else if(f==wb){g=e.getAttribute(rb);if(g){try{z=eval(g)}catch(a){alert(ub+g+xb)}}}}}}
function F(a){var b=u[a];return b==null?null:b}
function G(a,b){var c=x;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(A){A(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=n.createElement(yb);a.src=zb;a.id=Q;a.style.cssText=Ab;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Bb});a.contentWindow.location.replace(t+L)}}
w[Cb]=function(){return /(android|iphone|ipod|ipad)/i.test(window.navigator.userAgent)?Db:Eb};v[Cb]={mobilesafari:0,not_mobile:1};w[Fb]=function(){{var a=window.navigator.userAgent.toLowerCase();if(a.indexOf(Gb)!=-1||(a.indexOf(Hb)!=-1||(a.indexOf(Ib)!=-1||(a.indexOf(Jb)!=-1||a.indexOf(Kb)!=-1)))){var b=document.location.href;if(b.indexOf(Lb)===0){return Mb}}return Nb}};v[Fb]={no:0,yes:1};w[Ob]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Pb)!=-1}())return Pb;if(function(){return b.indexOf(Qb)!=-1}())return Rb;if(function(){return b.indexOf(Sb)!=-1&&n.documentMode>=9}())return Tb;if(function(){return b.indexOf(Sb)!=-1&&n.documentMode>=8}())return Ub;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Vb;if(function(){return b.indexOf(Wb)!=-1}())return Xb;return Yb};v[Ob]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};mvpdemo.onScriptLoad=function(){if(I){r=true;C()}};mvpdemo.onInjectionDone=function(){q=true;o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:Zb,millis:(new Date).getTime(),type:Y});C()};E();D();var K;var L;if(B()){if(m.external&&(m.external.initModule&&m.external.initModule(Q))){m.location.reload();return}L=$b;K=P}o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:_b});if(!B()){try{G([Db,Mb,Rb],ac);G([Eb,Nb,Pb],bc);G([Eb,Mb,Rb],cc);G([Eb,Nb,Ub],dc);G([Eb,Nb,Rb],ec);G([Db,Nb,Rb],fc);G([Eb,Nb,Tb],gc);G([Eb,Nb,Xb],hc);K=x[H(Cb)][H(Fb)][H(Ob)];var M=K.indexOf(ic);if(M!=-1){y=Number(K.substring(M+1));K=K.substring(0,M)}L=K+jc}catch(a){return}}var N;function O(){if(!s){s=true;C();if(n.removeEventListener){n.removeEventListener(kc,O,false)}if(N){clearInterval(N)}}}
if(n.addEventListener){n.addEventListener(kc,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(n.readyState)){J();O()}},50);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:Zb,millis:(new Date).getTime(),type:T});n.write(lc)}
mvpdemo();